### ISSUE TITLE
Wrong volume mapping in doc

### ISSUE THREAD

**Issue by btrscott** [dgraziotin/osx-docker-mysql#2]
Where it says:

Loading your custom MySQL files

If you wish to mount a MySQL folder locally, so that MySQL files are saved on your OS X machine, run the following instead:

docker run -i -t -p "3306:3306" -v ${PWD}/mysql:/mysql --name db dgraziotin/mysql
The MySQL database will thus become persistent at each subsequent run of your image.

---

I think the volume should map to /var/lib/mysql in the container.

So I would think the command should be:

docker run -i -t -p "3306:3306" -v ${PWD}/mysql:/var/lib/mysql --name db dgraziotin/mysql

Thoughts?

**Comment by dgraziotin** [comment]
Thanks!
